### ISSUE TITLE
Error when using nhd.byids("COMID", main.index.tolist()) (River Elevation and Cross-Section example)

### ISSUE THREAD

**Issue by LucRSquared** [hyriver/pynhd#60]
**What happened**:
I'm just trying to run the example notebook ["River Elevation and Cross-Section"](https://docs.hyriver.io/notebooks/cross_section.html)

I got an error at cell 13 when trying to query the flowlines by COMID

![image](https://user-images.githubusercontent.com/25012708/179627141-0bc7e143-a18e-45da-968a-cbfd9db8804d.png)

I get a `JSONDecodeError`

![image](https://user-images.githubusercontent.com/25012708/179627261-832287d2-7081-4d48-8bf2-1bad6b18dde1.png)

**Minimal Complete Verifiable Example**:
This simple code produces the same error:
```python
nhd = NHD("flowline_mr")
main_nhd = nhd.byids('COMID',['1722317'])
```

**Environment**:

<details><summary>Output of <tt>pynhd.show_versions()</tt></summary>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
libhdf5: 1.12.1
libnetcdf: 4.8.1

aiodns: 3.0.0
aiohttp: 3.8.1
aiohttp-client-cache: 0.7.1
aiosqlite: 0.17.0
async-retriever: 0.3.3
bottleneck: 1.3.4
brotli: installed
cchardet: 2.1.7
click: 8.1.3
cytoolz: 0.11.2
dask: 2022.6.1
defusedxml: 0.7.1
folium: 0.12.1.post1
geopandas: 0.11.0
lxml: 4.9.0
matplotlib: 3.4.3
netCDF4: 1.5.8
networkx: 2.8.4
numpy: 1.23.0
owslib: 0.25.0
pandas: 1.4.3
py3dep: 0.0
pyarrow: 6.0.0
pydantic: 1.9.1
pydaymet: 0.13.2
pygeohydro: 0.13.2
pygeoogc: 0.13.2
pygeos: 0.12.0
pygeoutils: 0.13.2
pynhd: 0.13.2
pyproj: 3.3.1
pytest: None
pytest-cov: None
rasterio: 1.2.10
requests: 2.28.0
requests-cache: 0.9.4
richdem: None
rioxarray: 0.11.1
scipy: 1.8.1
shapely: 1.8.2
tables: None
ujson: 5.3.0
urllib3: 1.26.9
xarray: 2022.3.0
xdist: None
yaml: 6.0
```

</details>

**Comment by cheginit** [comment]
It sounds like when you ran the notebook the [NHD web service](https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer) that the `NHD` class uses was down. I just reran the notebook and it worked just fine.

You can see that the function throws `ServiceError` exception (below `JSONDecodeError`) which indicates that service is not working.

By the way, other than the `NHD` class you can also use `WaterData` class to get the medium-res flowlines.

**Comment by LucRSquared** [comment]
Thank you! I just retried and it worked. Thanks for the `WaterData` tip! I'm closing the issue.
