### ISSUE TITLE
flow_trace() only returns one upstream river reach

### ISSUE THREAD

**Issue by mheberger** [hyriver/pynhd#63]
I expected the flow_trace() function to return all of the upstream river reaches, but it is only returning one. I think this is because the NLDI API changed, and now requires `distance` as a parameter. 
https://waterdata.usgs.gov/blog/nldi_update/#distance-is-now-a-required-query-parameter

```
import pynhd
pygeoapi = pynhd.PyGeoAPI()
lng, lat = -73.82705, 43.29139
trace = pygeoapi.flow_trace((lng, lat),  crs="epsg:4326", direction="up")
print(len(trace))
```

returns 1
(expected this watershed to contain dozens or even hundreds of river reaches).

**Comment by cheginit** [comment]
This is the expected results from `pygeoapi`'s `flowtrace` function that is to find the closest flowline to a point of interest. The functionality that you're looking for is in the `NLDI`'s class. You can use `navigate_byloc` method of this class to get the flowlines (or any other feature that NLDI supports). Please refer to its documentation for more details, which can be found [here](https://docs.hyriver.io/autoapi/pynhd/pynhd/index.html#pynhd.pynhd.NLDI.navigate_byloc)

**Comment by mheberger** [comment]
Got it, thanks! I think the naming is a little confusing. When I read "flow trace," it sounds like following a parcel of water upstream or downstream.

**Comment by cheginit** [comment]
I can see it being interpreted that way as well. I used the same name that PyGeoAPI uses to be consistent with it.
