### ISSUE TITLE
pynhd and shapely import error

### ISSUE THREAD

**Issue by rmcd-mscb** [hyriver/pynhd#64]
### What happened?

When creating a conda environment, with dependencies, pynhd and shapely<2.0, importing pynhd results in a shapely import error.

### Minimal Complete Verifiable Example

```Python
mamba create -n hyrtest pynhd "shapely<2.0"

In terminal with hyrtest activated:
python
import pynhd
```

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [X] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
❯ python
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynhd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmcd/mambaforge/envs/hyrtest/lib/python3.11/site-packages/pynhd/__init__.py", line 9, in <module>
    from pynhd.core import AGRBase, GeoConnex, ScienceBase
  File "/home/rmcd/mambaforge/envs/hyrtest/lib/python3.11/site-packages/pynhd/core.py", line 15, in <module>
    from pygeoogc import ArcGISRESTful, ServiceURL
  File "/home/rmcd/mambaforge/envs/hyrtest/lib/python3.11/site-packages/pygeoogc/__init__.py", line 13, in <module>
    from pygeoogc.pygeoogc import WFS, WMS, ArcGISRESTful, ServiceURL
  File "/home/rmcd/mambaforge/envs/hyrtest/lib/python3.11/site-packages/pygeoogc/pygeoogc.py", line 11, in <module>
    from shapely import LineString, MultiPoint, MultiPolygon, Point, Polygon
ImportError: cannot import name 'LineString' from 'shapely' (/home/rmcd/mambaforge/envs/hyrtest/lib/python3.11/site-packages/shapely/__init__.py)
```

### Environment

<details>

</details>

**Comment by rmcd-mscb** [comment]
FYI - adding python=3.9 to above `mamba create` command results in the same error.

**Comment by rmcd-mscb** [comment]
pinning pynhd and pygeoogc back a few versions works

mamba create -n hyrtest_39 python=3.9 pynhd=0.13.6 "shapely<2.0" pygeoogc=0.13.6

**Comment by cheginit** [comment]
Rich, thanks for reporting the issue.

The new HyRiver libraries (0.14) drop support for `shapely<2.0`. So, since you're pinning `shapely<0.2`, it does correctly install the previous version of `pynhd` (0.13.12) but installs `pygeoogc` (0.14) since `shapely` is not a dependency for `pygeoogc`. So, as a workaround, you need to pin `pygeoogc<0.14`:

```bash
mamba create -n hyrtest pynhd "shapely<2.0" 'pygeoogc<0.14'
```

**Comment by cheginit** [comment]
I fixed the issue in `pygeoogc`. Though, you need to wait for an hour or so, for `conda-forge` to build the fix and add it to their repository.

**Comment by rmcd-mscb** [comment]
Thanks @cheginit!
