### ISSUE TITLE
Fail to extract watershed boundary 

### ISSUE THREAD

**Issue by zeweima** [hyriver/pynhd#70]
### What happened?

Hi, 

I am trying to use "nldi.get_basins" to extract the upstream boundary of a gauge. However, it returns an error. I tried the example, and it also failed. (see the attachment)

![image](https://github.com/hyriver/pynhd/assets/33514529/eda40425-f468-4cf8-9d0d-7a51dfa7fbab)

All the best,
Zewei

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>
SYS INFO
--------
commit: None
python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
python-bits: 64
OS: Linux
OS-release: 5.15.120+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.12.2
libnetcdf: 4.9.3-development

PACKAGE                VERSION
-------------------------------
aiohttp                3.8.6
aiohttp-client-cache   0.10.0
aiosqlite              0.19.0
async-retriever        0.15.2
bottleneck             N/A
click                  8.1.7
cytoolz                0.12.2
defusedxml             0.7.1
folium                 0.14.0
geopandas              0.13.2
h5netcdf               1.3.0
hydrosignatures        0.15.2
joblib                 1.3.2
matplotlib             3.7.1
multidict              6.0.4
netcdf4                1.6.5
networkx               3.2.1
numba                  0.58.1
numpy                  1.23.5
owslib                 0.29.3
pandas                 1.5.3
py3dep                 0.15.2
py7zr                  N/A
pyarrow                9.0.0
pydaymet               0.15.2
pyflwdir               N/A
pygeohydro             0.15.2
pygeoogc               0.15.2
pygeoutils             0.15.2
pynhd                  0.15.2
pynldas2               0.15.2
pyogrio                N/A
pyproj                 3.6.1
rasterio               1.3.9
requests               2.31.0
requests-cache         1.1.0
rioxarray              0.15.0
scipy                  1.11.3
shapely                2.0.2
ujson                  5.8.0
url-normalize          1.4.3
urllib3                2.0.7
xarray                 2023.7.0
yarl                   1.9.2
-------------------------------

</details>

**Comment by cheginit** [comment]
Unfortunately, I cannot reproduce this error. Can you try creating a fresh env with only `pynhd` installed, so we can narrow down the issue?

I tried it with the same `pynhd` version that you have (0.15.2) and it works:

<img width="560" alt="image" src="https://github.com/hyriver/pynhd/assets/13016644/fa9c78b2-de3c-4a11-8dc9-c84e1bbc7a6c">

**Comment by zeweima** [comment]
Thanks for checking! I think it might be some comparable issues on the Google Colab now. I try on my own PC with new env, it works well. 

All the best,
Zewei

**Comment by cheginit** [comment]
Sure, if you still have this issue after creating a new env, please reopen this issue.
