### ISSUE TITLE
Trying to download huc08 feature, running into error

### ISSUE THREAD

**Issue by ehinman** [hyriver/pynhd#81]
### What happened?

I am trying to download a geopandas geodataframe of a single HUC08 using `WaterData`. However, I am getting an error message that perhaps my inputs are invalid? Generally, I have a really hard time knowing what the options are for these different layers. Some of the links out take me to equally confusing API pages, so more documentation would be helpful if possible.

### What did you expect to happen?

I expect the line of code to return a geopandas gdf.

### Minimal Complete Verifiable Example

```Python
from pynhd import WaterData

gdf = WaterData('huc08').byid('huc8',['07090001'])
```

### MVCE confirmation

- [X] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [x] Complete example — the example is self-contained, including all data and the text of any traceback.
- [x] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Relevant log output

```Python
---------------------------------------------------------------------------
InputValueError                           Traceback (most recent call last)
Cell In[4], line 1
----> 1 gdf = WaterData('huc08').byid('huc8',['07090001'])

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/pynhd/pynhd.py:507, in WaterData.byid(self, featurename, featureids)
    503 def byid(
    504     self, featurename: str, featureids: Sequence[int | str] | int | str
    505 ) -> gpd.GeoDataFrame:
    506     """Get features based on IDs."""
--> 507     resp = self.wfs.getfeature_byid(
    508         featurename,
    509         featureids,
    510     )
    511     resp = cast("list[dict[str, Any]]", resp)
    512     features = self._to_geodf(resp)

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/pygeoogc/pygeoogc.py:683, in WFS.getfeature_byid(self, featurename, featureids)
    680 else:
    681     feat_vals = ", ".join(f"{fid}" for fid in set(featureids))
--> 683 return self.getfeature_byfilter(
    684     f"{featurename} IN ({feat_vals})", method="POST", sort_attr=featurename
    685 )

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/pygeoogc/pygeoogc.py:735, in WFS.getfeature_byfilter(self, cql_filter, method, sort_attr)
    733 else:
    734     headers = {"content-type": "application/x-www-form-urlencoded"}
--> 735     resp = ar.retrieve_text([self.url], [{"data": payload, "headers": headers}], "POST")
    736 try:
    737     nfeatures = int(resp[0].split(self.nfeat_key)[-1].split(" ")[0].strip('"'))

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/async_retriever/async_retriever.py:498, in retrieve_text(urls, request_kwds, request_method, max_workers, cache_name, timeout, expire_after, ssl, disable, raise_status)
    437 def retrieve_text(
    438     urls: Sequence[StrOrURL],
    439     request_kwds: Sequence[dict[str, Any]] | None = None,
   (...)
    447     raise_status: bool = True,
    448 ) -> list[str]:
    449     r"""Send async requests and get the response as ``text``.
    450 
    451     Parameters
   (...)
    496     '01646500'
    497     """
--> 498     return retrieve(
    499         urls,
    500         "text",
    501         request_kwds,
    502         request_method,
    503         max_workers,
    504         cache_name,
    505         timeout,
    506         expire_after,
    507         ssl,
    508         disable,
    509         raise_status,
    510     )

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/async_retriever/async_retriever.py:394, in retrieve(urls, read_method, request_kwds, request_method, max_workers, cache_name, timeout, expire_after, ssl, disable, raise_status)
    330 def retrieve(
    331     urls: Sequence[StrOrURL],
    332     read_method: Literal["text", "json", "binary"],
   (...)
    341     raise_status: bool = True,
    342 ) -> RESPONSE:
    343     r"""Send async requests.
    344 
    345     Parameters
   (...)
    392     '01646500'
    393     """
--> 394     inp = BaseRetriever(
    395         urls,
    396         read_method=read_method,
    397         request_kwds=request_kwds,
    398         request_method=request_method,
    399         cache_name=cache_name,
    400     )
    402     if not disable:
    403         disable = os.getenv("HYRIVER_CACHE_DISABLE", "false").lower() == "true"

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/async_retriever/_utils.py:175, in BaseRetriever.__init__(self, urls, file_paths, read_method, request_kwds, request_method, cache_name)
    170     self.read_method = "read" if read_method == "binary" else read_method
    171     self.r_kwds = (
    172         {"content_type": None, "loads": json.loads} if read_method == "json" else {}
    173     )
--> 175 self.url_kwds = self.generate_requests(urls, request_kwds, self.file_paths)
    177 self.cache_name = create_cachefile(cache_name)

File /opt/homebrew/Caskroom/miniforge/base/envs/blackmarblepy-env/lib/python3.12/site-packages/async_retriever/_utils.py:208, in BaseRetriever.generate_requests(urls, request_kwds, file_paths)
    206 if not_found:
    207     invalids = ", ".join(not_found)
--> 208     raise InputValueError(f"request_kwds ({invalids})", list(session_kwds))
    210 return zip(url_id, urls, request_kwds)

InputValueError: Given request_kwds (data, headers) is invalid. Valid options are:
self
method
str_or_url
expire_after
refresh
kwargs
```

### Anything else we need to know?

I received the same error using python 3.13.0 and 3.12.0.

### Environment

<details>
SYS INFO
--------
commit: ff9c83f191b35ed87574555f823bdddaeb70f71d
python: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]
python-bits: 64
OS: Darwin
OS-release: 22.6.0
machine: arm64
processor: arm
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.14.3
libnetcdf: 4.9.2

PACKAGE                VERSION
-------------------------------
aiodns                 N/A
aiohttp                3.10.10
aiohttp-client-cache   0.12.4
aiosqlite              0.20.0
async-retriever        0.15.0
bottleneck             N/A
brotli                 1.1.0
click                  8.1.7
cytoolz                1.0.0
dask                   N/A
defusedxml             0.7.1
folium                 0.18.0
geopandas              1.0.1
h5netcdf               N/A
hydrosignatures        N/A
lxml                   5.3.0
matplotlib             3.9.2
netCDF4                1.7.1
networkx               3.4.2
numba                  N/A
numpy                  2.1.3
owslib                 0.32.0
pandas                 2.2.3
py3dep                 N/A
pyarrow                18.0.0
pydaymet               N/A
pygeohydro             N/A
pygeoogc               0.15.1
pygeos                 N/A
pygeoutils             0.15.2
pynhd                  0.15.1
pynldas2               N/A
pyproj                 3.7.0
pytest                 N/A
pytest-cov             N/A
rasterio               1.4.2
requests               2.32.3
requests-cache         1.2.1
richdem                N/A
rioxarray              0.17.0
scipy                  1.14.1
shapely                2.0.6
tables                 N/A
ujson                  5.10.0
urllib3                2.2.3
xarray                 2024.10.0
xdist                  N/A
yaml                   N/A
-------------------------------

</details>

**Comment by cheginit** [comment]
Please update to the latest HyRiver versions (v0.18) and try again (yours is v0.15). This sounds like an issue with conflicting versions. I ran your code with the latest version and it worked.

**Comment by cheginit** [comment]
No problem. It happens. I think there are some packages in your env that require a dependency no compatible with the latest version, or you're mixing installation from pip and conda in your env. I normally create an env file and set a min version for HyRiver packages to the latest series (`>=0.18`, for example) just to be sure. BTW, I recommend using `micromamba` instead of `mamba`, it's lightweight, and you don't have to manage a base env. You can install it with `brew` and then do:

```bash
alias mb="$(brew --prefix)/bin/micromamba"
mb config append channels conda-forge
mb config append channels nodefaults
mb config set channel_priority strict
mkdir -p $HOME/micromamba/envs/completion
mb shell completion
```

I also have these aliases in my `~/.zshrc`:

```bash
alias mb="micromamba"
alias mbu="micromamba update --all"
alias mbi="micromamba install"
alias mbf="micromamba env create -f"
alias mbc="micromamba create -n"
alias mbr="micromamba remove --all -n"
alias mbq="micromamba repoquery"
alias mbe="micromamba update -f"
alias mba="micromamba activate"
```
